### ISSUE TITLE
Mac do not sleep while Al Dente Pro is running

### ISSUE THREAD

**Issue by spsisys** [AppHouseKitchen/AlDente-Charge-Limiter#1047]
**Describe the bug**
Read the title. There are many requests about this problem from 2022.

**To Reproduce**
Just open the app. Sleep menu option is disabled and sleep & sleep displays doesn't work any more.

**Expected behavior**
I think it's obvious.

**Screenshots**
Al Dentro Pro Running:
![CleanShot 2023-09-23 at 18 14 38@2x](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/2944219/aa33d46c-c108-4d2c-bdeb-9773a201fcc7)
![CleanShot 2023-09-23 at 18 16 23@2x](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/2944219/05486a8a-b1d2-46d1-b297-e65dc6a9df3f)

Al Dente Pro Closed:
The system go to sleep properly. 
![CleanShot 2023-09-23 at 18 20 16@2x](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/2944219/e21890a0-0149-42af-a99b-0862fc80e3e6)

**MacBook 
![CleanShot 2023-09-23 at 18 21 02@2x](https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/2944219/a6514a0f-7ae8-4d6d-a6b7-934e22ee537f)
ase complete the following information):**

**Additional context**

**Comment by MatthiasKerbl** [comment]
Hi @spsisys,

This is actually the intended behavior of AlDente Pro when the Discharge feature is active to ensure discharge works in all scenarios such as the clamshell mode for example. Since you have Automatic Discharge enabled and you are currently discharging, sleep is disabled by AlDente.
Also, when discharging for the first time, a short explanation should appear explaining this scenario.
<img width="372" alt="Notification" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/33470003/55c253f7-aadc-4a28-b325-4bb43254ebbc">

Best,
Matthias

**Comment by spsisys** [comment]
@MatthiasKerbl Thanks for your answer. All clear! But I need the sleep mode active even when the battery is discharged. I understand that it's a so easy step to cancel Discharge Mode, but it's not my workflow because I've to leave my workplace often, and the app is installed to prevent the battery from further charging. Nevertheless, I'll check the new workflow before uninstall the app. Cheers!
