### ISSUE TITLE
Override disabled sleep option in automatic discharge

### ISSUE THREAD

**Issue by PaulShiLi** [AppHouseKitchen/AlDente-Charge-Limiter#1051]
There are a lot of complaints about how sleep is disabled when automatic discharge is enabled and I find it a bit of a hassle to manually disable by having to open the aldente app and disable this option whenever I go outside and have to leave my mac in my room when connected to external monitors. With sleep disabled, this means that my monitors are on with no way of turning them off besides having to manually toggle this option on/off when my mac is above the discharge limit.

For the solution, I would suggest having an additional toggle below the Automatic Discharge toggle allowing the overriding of sleep by disabling it when the sleep button is pressed and automatically re-enabling it when the computer wakes back up

**Comment by MatthiasKerbl** [comment]
Hi @PaulShiLi,

I am not sure I understand your issue completely. Please answer the following question so that I can assess your situation better.

1. Do you have the setting "Disable Sleep until Charge Limit" enabled?
2. Do you charge your MacBook through the external monitor or with a charger?
3. Do you have the lid closed/do you use your MacBook in clamshell mode?
4. Which MacBook model do you use?

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
Hi @PaulShiLi,

It's been a while since we last heard from you, so I'm gonna go ahead and close this issue for now. If you need to come back to it later, just let me know. I'm here to help and can easily reopen it for you.

Best,
Matthias
