### ISSUE TITLE
SystemUIserver drying CPU and discharging.

### ISSUE THREAD

**Issue by SphereSK** [AppHouseKitchen/AlDente-Charge-Limiter#1065]
**Describe the bug**
For some reason there is still running systemUIserver which is drying CPU and discharging to 2% of battery.

**To Reproduce**
Aldente running. Charging to 80%. Remove power outlet.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model: 13-inch, 2020, Four Thunderbolt 3 ports
 - macOS version: 14.0 (23A344)
 - AlDente Pro
 - AlDente Version: 1.22.2
 - List of all enabled/disabled settings in AlDente:

<img width="418" alt="SCR-20231005-oqnc" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/52425935/caeff939-2004-4849-8dd7-55ef4fec0d21">

<img width="424" alt="SCR-20231005-oqks" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/52425935/a31e5664-a355-4fcd-b376-f704f312bbb0">

**Additional context**
i quit AlDente and systemUIserver are not running anymore. So it looks like that it is somehow linked with aldente.

**Comment by MatthiasKerbl** [comment]
Hi @SphereSK,

It is rather unlikely that the SystemUIserver has anything to do with AlDente.
This is a common macOS issue and can be caused by many things such as this one for example https://news.numlock.ch/mac_os_x/macos-systemuiserver-eating-your-cpu-check-your-ethernet-connection

Best,
Matthias
