### ISSUE TITLE
2 different battery ratings

### ISSUE THREAD

**Issue by burak1337** [AppHouseKitchen/AlDente-Charge-Limiter#1098]
<img width="1440" alt="Screenshot 2023-11-10 at 22 10 48" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/41003932/50db2714-d33d-43f1-9612-5fd3c6b2c9c1">

The charge value in the app is 71, but the normal battery is 73. These app values are not compatible with the battery value on the computer. What is the reason for this?

**Comment by MatthiasKerbl** [comment]
Hi @burak1337,

This is most likely because you have the Hardware Battery Percentage feature enabled in AlDente.
You can read more about this feature here ["Feature Explanation: Hardware Battery Percentage"](https://apphousekitchen.com/feature-explanation-hardware-battery-percentage/).

Best,

Matthias
