### ISSUE TITLE
Different Icon Style when Discharging

### ISSUE THREAD

**Issue by jnnsrctr** [AppHouseKitchen/AlDente-Charge-Limiter#1125]
I really like seeing when the MacBook isn't charging. For that, the status icons are great. But, I personally don't like the discharging icon. I am used to the classic Mac battery icon, where I can estimate the charge level by the percentage of the icon, that is filled. This way I know how much time I have when portable, without the percentage giving me anxiety 😃

Maybe there is a way to easily allow me to switch icon styles? Like a rule or a shortcut: when disconnected, change icon style

Premium solution would obviously be a setting 😉

<img width="98" alt="Screenshot 2023-12-13 at 15 44 51" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/99033602/78d4e77e-9691-4807-83e4-cc8608ed40f1">

**Comment by MatthiasKerbl** [comment]
Hi @jnnsrctr,

Thank you for the input. In general, we are trying to keep AlDente as simple as possible but still trying to offer as much customizability as possible. Since there are already two workarounds for your preference, either activating the percentage icon or switching to a different battery icon, I do not see the need to add more settings for this. However, we might improve the general customizability of the menubar icon in the future.

Hope you understand. :)

Best,
Matthias
