### ISSUE TITLE
Unable to sleep while AlDente is running

### ISSUE THREAD

**Issue by skhaz** [AppHouseKitchen/AlDente-Charge-Limiter#1169]
I am a user of AlDente Pro, and I am very satisfied with the app. However, after the last update, my MacBook won't sleep. I need to quit AlDente for it to be able to sleep. I have checked all the settings, and it is supposed to allow sleeping.

Any ideas?

**Comment by MatthiasKerbl** [comment]
Hi @skhaz,

I am glad to hear that you like AlDente. :)
Please answer the following questions so that we can assess your issue better:

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**
Add any other context about the problem here.

Cheers,
Matthias

**Comment by skhaz** [comment]
There is no error, I just open AlDente and I am unable to sleep my macbook, it is a m2 air, it was working fine last week.

**Comment by skhaz** [comment]
<img width="288" alt="Screenshot 2024-02-19 at 13 21 14" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/46259/1ba8ca47-228f-4a75-8eaf-9881c52a576a">
<img width="544" alt="Screenshot 2024-02-19 at 13 21 24" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/46259/a9b0c840-bf28-4abc-8c80-134e14bde03a">

**Comment by MatthiasKerbl** [comment]
Hi @skhaz,

Thank you for providing more details.
Do you use your MacBook with an external display in clamshell mode?
Are you currently Discharging?
If possible, please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on [How to generate and share a debug file](https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/) on our blog.

Best,
Matthias

**Comment by skhaz** [comment]
Yes and yes. Switching to charging, I was able to put it in sleep! I'm sorry, I didn't know that the way it was before wasn't possible. All good and thank you!
