### ISSUE TITLE
Not shiet Changerging

### ISSUE THREAD

**Issue by alsyundawy** [AppHouseKitchen/AlDente-Charge-Limiter#1273]
i am new using aldente pro from pirate to buying license original

My Mac Intel set 93%

but what i get 
when using pirate 1.27 no issue
when using my license 1.27.3 not / stop charge 

 what the fuck with ALDente Pro , can i req refund about shiet?

then they no have any email for support, rubish support?

**Comment by MatthiasKerbl** [comment]
Hi @alsyundawy,

When you bought AlDente Pro, you got our premium support email address in the purchasing emails and you have more information about it on our [website](https://apphousekitchen.com/support/).
You can request a refund within the first two weeks of purchase. Just write to our support.
Also, since you used an illegal pirated version of AlDente, this issue will be deleted.

Best,
Matthias
