### ISSUE TITLE
Heat protection ignored during calibration

### ISSUE THREAD

**Issue by mickgotwings** [AppHouseKitchen/AlDente-Charge-Limiter#1283]
**MacBook (please complete the following information):**
 - MacBook Model (https://support.apple.com/en-us/HT201608): MacBookPro18,4 M1 Max
 - macOS Version (https://support.apple.com/en-us/HT201260): Sonoma 14.5
 - Charger Model (Apple, Third Party, Wattage,...): USB-C PD via MSI MEG 342C
 - Charging Cable (MagSafe 2, MagSafe 3, USB-C, Apple, Third Party,...): USB-C
 - AlDente Pro or AlDente Free: Pro
 - AlDente Version: 1.27.3
 - List or add screenshots of all enabled/disabled settings in AlDente:
 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 - External Monitor connected? Yes
 - MacBook used in Clamshell Mode (with the lid closed)? Yes

**Describe the bug**
During my last battery calibration, heat protection seemed to be ignored during the third phase (charge to 100%).

**To Reproduce**
1. Set your heat protection to a setting lower, than what your battery usually heats up during charge
2. Start calibration
3. Wait for phase 3 (charge to 100%)
4. Open settings
5. Make sure that the battery is still charging, while battery temperature is higher, than the limit set in heat protection

**Expected Behavior**
Heat protection prevents battery from overheating during the calibration

**Screenshots and Screen Recordings**
![Screenshot 1](https://github.com/user-attachments/assets/d8ccfcb0-5b88-4eb2-9ab3-d77a210d5ddd)

**Additional context**
Not sure if it's a bug, or not. If this behavior is expected, it should at least clearly state so in the docs.
As far as I'm concerned, AlDente prevents macOS from controlling the charging entirely. If previous is correct, this behavior could potentially damage your battery by overheating it.

P.S. I use heat protection all the time, none of the settings were altered during the calibration process.

**Comment by MatthiasKerbl** [comment]
Hi @mickgotwings,

We decided to disable heat protection during calibration mode to not further prolong the calibration. Also, since the calibration mode is only used roughly every two weeks, the negative side effects are low. Furthermore, we noticed a slightly better outcome if the calibration was not interrupted.

We have added this explanation to both articles on our blog:
[Feature Explanation: Heat Protection](https://apphousekitchen.com/feature-explanation-heat-protection/)
[Feature Explanation: Calibration Mode](https://apphousekitchen.com/feature-explanation-calibration-mode-2/)

Furthermore, AlDente does not override the whole charging behavior from macOS. This means that safety features are still enabled.

Best,
Matthias
