### ISSUE TITLE
Need to install helper after every reboot on aldente pro

### ISSUE THREAD

**Issue by marcjuhl** [AppHouseKitchen/AlDente-Charge-Limiter#1304]
**MacBook**
 - MacBook Model (2021 m1pro macbook pro 14"):
 - macOS Version (15.1):
 - Charger Model (official 67w charger that came with it):
 - Charging Cable (usb c and magsafe 3):
 - AlDente Pro
 - AlDente Version: 1.27.3
 - List or add screenshots of all enabled/disabled settings in AlDente:
 - 
<img width="509" alt="Screenshot 2024-08-30 at 18 15 37" src="https://github.com/user-attachments/assets/862ead8d-cf5f-40c7-8833-b8fecb6eec29">
<img width="509" alt="Screenshot 2024-08-30 at 18 15 41" src="https://github.com/user-attachments/assets/83859c66-9f0e-4d5e-a8a1-d64dff405256">
<img width="509" alt="Screenshot 2024-08-30 at 18 15 48" src="https://github.com/user-attachments/assets/b20e491c-f19f-439b-9a0b-355f561faf40">
<img width="509" alt="Screenshot 2024-08-30 at 18 15 52" src="https://github.com/user-attachments/assets/b9ef09a4-a67a-4413-bc4c-07584b6a2832">
<img width="509" alt="Screenshot 2024-08-30 at 18 15 57" src="https://github.com/user-attachments/assets/9809163d-3908-4899-a45c-4f453bf65c42">
<img width="509" alt="Screenshot 2024-08-30 at 18 15 31" src="https://github.com/user-attachments/assets/5faa78c0-1fe2-4755-9173-74fbb484645f">

 - Please share a debug file the next time this happens so that we can assess this issue better. You can find a guide on How to generate and share a debug file on our blog(https://apphousekitchen.com/how-to-generate-and-share-a-debug-file/).
 
 - External Monitor connected?
 no
 - MacBook used in Clamshell Mode (with the lid closed)?
 no

**Describe the bug**
Every time i restart my mac it asks for me to install the helper application, no matter if i already installed it..

**To Reproduce**
1. Restart your mac
2. click the aldente menu
3. it says i need to install the helper app even though i have

**Screenshots and Screen Recordings**
<img width="509" alt="Screenshot 2024-08-30 at 18 06 29" src="https://github.com/user-attachments/assets/71c30a87-cc36-47b6-bf0e-5982a5c5681e">

**Comment by marcjuhl** [comment]
Sorry heres the debug file 
https://drive.google.com/file/d/14FRUlTR7K6ra_f-NP5-lsfnR3OsWQr-1/view?usp=drive_link

**Comment by b159732000** [comment]
Me too on M1 Max, OS 14.6.1（23G93）

**Comment by MatthiasKerbl** [comment]
Hi everyone,

Usually, problems regarding the helper installation can be fixed with a simple restart of your MacBook.
If that does not work for you, please follow these steps:

- Please go to Finder navigate to /Library/PrivilegedHelperTools/ and delete the file: "com.apphousekitchen.aldente-pro.helper"
- Then, please navigate to Library/LaunchDaemons/ and remove "com.apphousekitchen.aldente-pro.helper.plist" 
- Also, remove your AlDente application and reboot your MacBook.
- Then, install it as if it was freshly downloaded.

At last, once the new helper is installed again, please check if AlDente is allowed to run in the background in the "Login Items" section of the macOS settings. This could also be the culprit.

Best,
Matthias

**Comment by marcjuhl** [comment]
That worked thanks!

**Comment by inspiredearth** [comment]
Same issue. Been occurring for months. Currently on macOS 15.3.1, on M1 platform.
Will try above mentioned manual deletion of helper file, etc.
