### ISSUE TITLE
Add Low Power Mode Button to Menu Bar Widget

### ISSUE THREAD

**Issue by ovq** [AppHouseKitchen/AlDente-Charge-Limiter#603]
The subject says it all. It would be nice to be able to toggle low-power mode via the AlDente menu bar.

**Comment by MatthiasKerbl** [comment]
Hi @ovq,

Good idea but I do not know if it is possible for third-party apps to alter these settings.
We will look into this.

Cheers,
Matthias

**Comment by andrewcrook** [comment]
> but I do not know if it is possible for third-party apps to alter these settings.

I think it can be done from` pmset` 

```
arm64 andrew@Andrews-MBP ~ % pmset -g  

System-wide power settings:
 SleepDisabled		1
Currently in use:
 standby              1
 Sleep On Power Button 1
 hibernatefile        /var/vm/sleepimage
 powernap             1
 networkoversleep     0
 disksleep            10
 sleep                1 (sleep prevented by bluetoothd, com.bombich.ccchelper, com.bombich.ccchelper, powerd, sharingd, com.apphousekitchen.aldente-pro)
 hibernatemode        3
 ttyskeepawake        1
 displaysleep         10 (display sleep prevented by com.apphousekitchen.aldente-pro)
 tcpkeepalive         1
 **lowpowermode         0**
 womp                 1
```

**Comment by andrewcrook** [comment]
Perhaps the feature should turn on automatically when battery life reaches a certain percentage set by the user.

**Comment by basmets6** [comment]
+1 on this. I'd prefer an on-off switch, since I typically have it on at all times unless I notice my performance lagging.

**Comment by andrewcrook** [comment]
Both options then

**Comment by DamonHD** [comment]
And I'd like low-power mode automatically engaged when any grid-friendly features are switched on.

BTW, in a brief since test on my MBA M1, typical draw from mains adaptor with an editor prompt open and a little bit of other activity was about 4.9W dropping to about 4.2W with low-power mode on, so a useful 15%/0.7W saving in that case.

http://www.earth.org.uk/Hey-Siri-Help-Flatten-The-Duck.html#Measured

Rgds

Damon

**Comment by xsnaruto** [comment]
The problem to me is I'd like to set low battery mode on when MacBook is using battery, but after aldent changed the battery as  discharging, the system will get into low battery mode, even the device still connected the power, this will cause many of function stop operating, such as iCloud photo sync etc. sometimes I forgot to manually turn sync on, I take MacBook out after a whole night with power connected, than I found out that none photos synced.

hope there's a way to let aldent turn off low battery mode after connected to the power and turn it on after detected the power is disconnected. for now, I just setup never turn on the low battery mode, because im easy to forget switch them, its not a good way to solve problem.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released AlDente 1.26.1 which includes a Low Power Mode setting. You can enable the Low Power Mode in Settings/Features/Low Power Mode. Also, the Right Click feature on the menubar icon is now customizable and can now be configured to trigger the Low Power Mode

To get AlDente 1.26.1 you just need to update within the app under Settings/General/Check for Updates.

Best,
Matthias

**Comment by e-kotov** [comment]
@MatthiasKerbl, love the feature! However, it's not immediately apparent whether the low power mode is activated. Currently, one must navigate to the system battery widget in the menu bar, click on it, and check the popup. Could you integrate a low power mode indicator directly into the AlDente menu bar icon or its popup with a single click? Additionally, incorporating a toggle for low power mode in the same popup would be extremely useful.

**Comment by MatthiasKerbl** [comment]
> @MatthiasKerbl, love the feature! However, it's not immediately apparent whether the low power mode is activated. Currently, one must navigate to the system battery widget in the menu bar, click on it, and check the popup. Could you integrate a low power mode indicator directly into the AlDente menu bar icon or its popup with a single click? Additionally, incorporating a toggle for low power mode in the same popup would be extremely useful.

Hi @e-kotov,

Thank you for your feedback and good to hear that you like the new feature.
You can see the Low Power Mode status in the AlDente popover when you have the Electrical Specs Sensor Data panel enabled in settings.
If you want to quickly enable/disable the Low Power Mode, please use the Right Click feature described above.
<img width="472" alt="Screenshot 2024-04-12 at 12 07 52" src="https://github.com/AppHouseKitchen/AlDente-Charge-Limiter/assets/33470003/609be2b0-d392-41e3-83f6-0c72aef4708b">

Best,
Matthias

**Comment by colinbrislawn** [comment]
> integrate a low power mode indicator directly into the AlDente menu bar icon or its popup with a single click?

This is what I was looking for!

> Also, the Right Click feature on the menubar icon is now customizable and can now be configured to trigger the Low Power Mode

Does this mean that you can configure this so that a right-click toggels low-power mode on and off?

(This the specific UX I'm looking for, so I'm trying to understand it before buying Al Dante.)

**Comment by MatthiasKerbl** [comment]
> > integrate a low power mode indicator directly into the AlDente menu bar icon or its popup with a single click?
> 
> This is what I was looking for!
> 
> > Also, the Right Click feature on the menubar icon is now customizable and can now be configured to trigger the Low Power Mode
> 
> Does this mean that you can configure this so that a right-click toggels low-power mode on and off?
> 
> (This the specific UX I'm looking for, so I'm trying to understand it before buying Al Dante.)

Hi @colinbrislawn,

Yes, you can configure AlDente Pro so that a right-click on the menu bar icon enables/disables the Low Power Mode.

Best,
Matthias

**Comment by FrancisMorelli** [comment]
@MatthiasKerbl What is low power mode? I've not found an explanation on the website like others features.

**Comment by e-kotov** [comment]
@FrancisMorelli it's Apple's default feature, see https://support.apple.com/en-gb/guide/mac-help/mh35848/mac

**Comment by FrancisMorelli** [comment]
> @FrancisMorelli it's Apple's default feature, see https://support.apple.com/en-gb/guide/mac-help/mh35848/mac

So, it's not an AlDente feature... does it only enable the built-in Apple feature?

**Comment by e-kotov** [comment]
> > @FrancisMorelli it's Apple's default feature, see https://support.apple.com/en-gb/guide/mac-help/mh35848/mac
> 
> @e-kotov  So, it's not an AlDente feature... does it only enable the built-in Apple feature?

That's what I would expect.

**Comment by tiagovaznunes-collab** [comment]
Hi, i have a MacBook Pro M5 and it has no low power or high power modes on the apple battery management (only pro, max and ultra have it). On the electrical specs menu, i have the low power mode described as disabled, but on the widget with the 3 icons (normal, battery saving, and a third one that i don’t know what’s for), says “low power mode” with a battery symbol with almost no battery. Since that’s not a button, i don’t know if it’s just there or it “thinks” my mac is in low power mode. Can you help? Thanks

**Comment by MatthiasKerbl** [comment]
> Hi, i have a MacBook Pro M5 and it has no low power or high power modes on the apple battery management (only pro, max and ultra have it). On the electrical specs menu, i have the low power mode described as disabled, but on the widget with the 3 icons (normal, battery saving, and a third one that i don’t know what’s for), says “low power mode” with a battery symbol with almost no battery. Since that’s not a button, i don’t know if it’s just there or it “thinks” my mac is in low power mode. Can you help? Thanks

Hi @tiagovaznunes-collab,

Apple lists the M5 MacBook Pro as officially supporting the low-power mode.
https://support.apple.com/en-gw/101613

Best,
Matthias

**Comment by tiagovaznunes-collab** [comment]
Hi Matthias,

Thanks for the prompt reply.

The M5 allows the user to choose normal, low poder mode and discharge mode on AL DENTE energy widget. What ela és with some doubts is that that widget is cales “low power mode” and i guess it should be names “Energy mode”. Like it is, even if i choose normal mode, i read on the widget name low power mode and I’m unsure that  my setup is working normally

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Matthias Kerbl ***@***.***>
Enviado: segunda-feira, fevereiro 16, 2026 8:33 AM
Para: AppHouseKitchen/AlDente-Battery_Care_and_Monitoring ***@***.***>
Cc: tiagovaznunes-collab ***@***.***>; Mention ***@***.***>
Assunto: Re: [AppHouseKitchen/AlDente-Battery_Care_and_Monitoring] Add Low Power Mode Button to Menu Bar Widget (Issue #603)

[https://avatars.githubusercontent.com/u/33470003?s=20&v=4]MatthiasKerbl left a comment (AppHouseKitchen/AlDente-Battery_Care_and_Monitoring#603)<https://github.com/AppHouseKitchen/AlDente-Battery_Care_and_Monitoring/issues/603#issuecomment-3907112148>

Hi, i have a MacBook Pro M5 and it has no low power or high power modes on the apple battery management (only pro, max and ultra have it). On the electrical specs menu, i have the low power mode described as disabled, but on the widget with the 3 icons (normal, battery saving, and a third one that i don’t know what’s for), says “low power mode” with a battery symbol with almost no battery. Since that’s not a button, i don’t know if it’s just there or it “thinks” my mac is in low power mode. Can you help? Thanks

Hi @tiagovaznunes-collab<https://github.com/tiagovaznunes-collab>,

Apple lists the M5 MacBook Pro as officially supporting the low-power mode.
https://support.apple.com/en-gw/101613

Best,
Matthias

**Comment by MatthiasKerbl** [comment]
> Hi Matthias,
> 
> Thanks for the prompt reply.
> 
> The M5 allows the user to choose normal, low poder mode and discharge mode on AL DENTE energy widget. What ela és with some doubts is that that widget is cales “low power mode” and i guess it should be names “Energy mode”. Like it is, even if i choose normal mode, i read on the widget name low power mode and I’m unsure that  my setup is working normally
> 
> Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
> […](#)

Hi @tiagovaznunes-collab,

Thank you for your feedback. We have already made some changes to clarify and simplify this feature. A new update will be released soon.

Best,
Matthias

**Comment by tiagovaznunes-collab** [comment]
But is my Mac working normally? I mean, the fact that the widget says “Low power mode” doesn’t mean the MacBook is on low power mode, right? It’s just the widget name…

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Matthias Kerbl ***@***.***>
Enviado: Monday, February 16, 2026 9:56:00 AM
Para: AppHouseKitchen/AlDente-Battery_Care_and_Monitoring ***@***.***>
Cc: tiagovaznunes-collab ***@***.***>; Mention ***@***.***>
Assunto: Re: [AppHouseKitchen/AlDente-Battery_Care_and_Monitoring] Add Low Power Mode Button to Menu Bar Widget (Issue #603)

[https://avatars.githubusercontent.com/u/33470003?s=20&v=4]MatthiasKerbl left a comment (AppHouseKitchen/AlDente-Battery_Care_and_Monitoring#603)<https://github.com/AppHouseKitchen/AlDente-Battery_Care_and_Monitoring/issues/603#issuecomment-3907505498>

Hi Matthias,

Thanks for the prompt reply.

The M5 allows the user to choose normal, low poder mode and discharge mode on AL DENTE energy widget. What ela és with some doubts is that that widget is cales “low power mode” and i guess it should be names “Energy mode”. Like it is, even if i choose normal mode, i read on the widget name low power mode and I’m unsure that my setup is working normally

Enviado a partir do Outlook para iOShttps://aka.ms/o0ukef
…

Hi @tiagovaznunes-collab<https://github.com/tiagovaznunes-collab>,

Thank you for your feedback. We have already made some changes to clarify and simplify this feature. A new update will be released soon.

Best,
Matthias
