### ISSUE TITLE
Calibration Mode gets disabled by changing Sailing Mode or Charge Limiter settings

### ISSUE THREAD

**Issue by gselsidi** [AppHouseKitchen/AlDente-Charge-Limiter#813]
I had battery calibration on, then i turned on sailing mode, and it disabled the calibration have to start all over again...... Please change this behavior. 

Also if you change the battery capacity at the top it disabled battery calibration, I was almost down a full cycle, and now have to restart.... kinda annoying

**Comment by MatthiasKerbl** [comment]
Hi @gselsidi,

I understand your frustration about the aborted Calibration Mode.
It's the first time that someone brings this up since usually, our users activate the Calibration mode, let it run, and then change the charge settings again.
I will put it on our list for future improvements but I hope you understand that it is not a priority at the moment.

Cheers,
Matthias

**Comment by gselsidi** [comment]
Yeah it’s fine not a big issue thanks

**Comment by Bachsau** [comment]
I also think it would just be more clear, if this was as special mode, that, while active overrides all other settings. You should also apply this change to the "Top Up" mode. Currently it moves the slider to 100% while active.

**Comment by MatthiasKerbl** [comment]
Hi @gselsidi,

We have just released AlDente 1.27 which now allows you to change the Sailing Range and Charge Limit while the Calibration Mode is active.

Best,
Matthias
